tmp_directory: /tmp/rd/

user_scripts: 
  # Scripts crunched to one file
  # Load these in proper order
  # Manpage depends on JS
  - manpage

user_styles: 
  - reset
  - milstil

keybindings:
  ctrl-shift-i: toggle_script speedread
  ctrl-shift-p: toggle_style reset
